var app=angular.module('reader',['ngRoute']);
app.config([
	'$routeProvider',
	function($routeProvider){
		$routeProvider.when('/',{
			templateUrl:'reader/login/login.html',
			controller:'loginCtrl'
		}).when('/bookshelf',{
			templateUrl:'reader/bookshelf/bookshelf.html',
			controller:''
		}).when('/readPage',{
			templateUrl:'reader/readPages/readPage.html',
			controller:'readCtrl'
		}).when('/bookmark',{
			templateUrl:'reader/readPages/bookmark.html',
			controller:'markCtrl'
		}).when('/notes',{
			templateUrl:'reader/readPages/note.html',
			controller:'notCtrl'
		})
	}
])